### ISSUE TITLE
Using dev build

### ISSUE THREAD

**Issue by dafabulousteach** [cyrilletuzi/nguniversal-expressengine-httpinterceptor#2]
Thank you so much for this repo!

Is it possible to use this with a dev build?

**Comment by cyrilletuzi** [comment]
It should work if you activate `--aot` (needed for Universal). Or as it is two different packages, you can stay in dev for the browser and in prod for the server : 
`ng build && ng build --prod --app universal --output-hashing=none`

**Comment by dafabulousteach** [comment]
Thank you for this!
