### ISSUE TITLE
AOT with different environments

### ISSUE THREAD

**Issue by dafabulousteach** [cyrilletuzi/nguniversal-expressengine-httpinterceptor#3]
This is more of a question:

Seeing that the universal app needs to be built with either an AOT or prod flag, are you able to build with either of those flags using different environments? So something like: ```npm build --app universal --aot --env=qa```

**Comment by cyrilletuzi** [comment]
Yes, I see no problem to this case, `--prod` is just a shortcut of these multiple options.
