### ISSUE TITLE
Azure deployment

### ISSUE THREAD

**Issue by nichovski** [cyrilletuzi/nguniversal-expressengine-httpinterceptor#4]
Hi @cyrilletuzi,

Thanks for the amazing project.

Have you tried to deploy to azure? On my side azure is throwing 

**remote: Invalid start-up command "npm run build && npm run server" in package.js                                                   on. Please use the format "node <script relative path>".**

Here is how my dist folder looks:

![image](https://user-images.githubusercontent.com/1162068/29495460-0adc95cc-85c0-11e7-986a-13fb7b5d51b9.png)

 Any suggestions regarding this issue?

Thanks

**Comment by cyrilletuzi** [comment]
The npm `start` script of this project is for dev only.

In prod, the build step should have been done already, and you just have to launch the server (ie. `node server.js`).

I don't know Azure but I suppose that like many tools it automatically launches the npm `start` script, so you should change it to `node server.js`.

**Comment by nichovski** [comment]
That works, thank you! 

But SSR is not working again. Do we need to change the port to something else or we need to leave it 3000?

Thanks

**Comment by cyrilletuzi** [comment]
It should be port 80.
