### ISSUE TITLE
Listening on http://localhost:3000 ERROR { Error: Uncaught (in promise): ReferenceError: localstorage is not defined ReferenceError: localstorage is not defined

### ISSUE THREAD

**Issue by dkmostafa** [cyrilletuzi/nguniversal-expressengine-httpinterceptor#5]
When i use localstorage this error os going on in the terminal, which is stopping the server side rendering.
any help

**Comment by cyrilletuzi** [comment]
Yes, that's normal as localStorage does not exist on server side. Read the section "Pitfall n°1 : being Universal compatible" of the blog post indicated in the Readme : https://medium.com/@cyrilletuzi/angular-server-side-rendering-in-node-with-express-universal-engine-dce21933ddce
