### ISSUE TITLE
Can you add at-list 2 components with routing between them 

### ISSUE THREAD

**Issue by TomasKatz** [cyrilletuzi/nguniversal-expressengine-httpinterceptor#8]
Can you add at-list 2 components with routing between them so that we can atlist see this works in a real application situation. Applications never consist of only one sentence in the home page.

**Comment by cyrilletuzi** [comment]
This repo is not supposed to do your app. ;) It was just a non official example for early beta testers. Official Universal is coming in CLI 1.6 very soon.
